general.import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
[window]
  decorations = "buttonless"
  blur = true

[font]
  size = 14

[font.normal]
  family = "JetBrainsMonoNL Nerd Font Propo"
  style = "Regular"

[font.bold]
  family = "JetBrainsMonoNL Nerd Font Propo"
  style = "Bold"

[font.italic]
  family = "JetBrainsMonoNL Nerd Font Propo"
  style = "Italic"

[font.bold_italic]
  family = "JetBrainsMonoNL Nerd Font Propo"
  style = "Bold Italic"

[[keyboard.bindings]]
  key = "Tab"
  mods = "Control"
  action = "SelectNextTab"

[[keyboard.bindings]]
  key = "Tab"
  mods = "Control|Shift"
  action = "SelectPreviousTab"

[[keyboard.bindings]]
  key = "Enter"
  mods = "Command"
  action = "ToggleFullscreen"

[selection]
  save_to_clipboard = true
